### ISSUE TITLE
Story: Als Nutzer möchte ich allgemeine Information über den botanischen Garten über das Menü einsehen können, damit ich mich auf meinen Besuch vorbereiten kann.

### ISSUE THREAD

**Issue by XMacca** [ASE-Projekte-WS-2021/ase-ws-21-botanist#10]
- Es gibt Informationen zu Öffnungszeiten, Parkplätze, Ansprechpartner.

**Comment by AAlesik** [comment]
Fließtext ist zwar pragmatisch, taktisch, nett aber eine Tabellarische Ansicht wäre besser...
