### ISSUE TITLE
Main Font wanted - a task for everyone

### ISSUE THREAD

**Issue by AAlesik** [ASE-Projekte-WS-2021/ase-ws-21-botanist#23]
It is essential that a fitting and represetative font will be picked, since our app evolves to greater parts around style.
We need:
- a handwriting-esk type of font
- if Serifs are wanted then something like "Venetian Renaissance Antiqua" 

Suggestions: in "Old Style" or alternatively a modern Style like "Modern No. 20" 
-> the ideal would be a rather slim font type, good to read and elegant

**Comment by polinaugnivenko** [comment]
https://fonts.google.com/specimen/Petrona?stylecount=8&category=Serif,Handwriting
