### ISSUE TITLE
Appium automated Testing

### ISSUE THREAD

**Issue by JJLo1** [ASE-Projekte-WS-2021/ase-ws-21-botanist#33]
Add Appium UI-Testing

**Comment by polinaugnivenko** [comment]
Automated Testing is ongoing, and is with further UI changes expanded and reworked, thus is an ongoing issue until the project's finish. For this reason it will be moved to phase 4.

**Comment by polinaugnivenko** [comment]
Automated Testing now updated for all UI changes
