### ISSUE TITLE
Marker onclick verhalten hinzufügen

### ISSUE THREAD

**Issue by JJLo1** [ASE-Projekte-WS-2021/ase-ws-21-botanist#43]
-->  führt zu area drawer auswahl

**Comment by Rosti97** [comment]
Marker gibt Daten an den Drawer weiter, welcher sich auch öffnet.
Bug: Man muss einmal zur Plant-Ansicht und zurück switchen, um die Pflanzen in dem Areal zu sehen

**Comment by JJLo1** [comment]
fixed
