### ISSUE TITLE
Drawer Fragment anlegen das informationen zu einem bereich darstellt

### ISSUE THREAD

**Issue by XMacca** [ASE-Projekte-WS-2021/ase-ws-21-botanist#7]
- Es gibt eine Übersicht an Bereichen
- Über die Bereiche kann herausgefunden werden, welches Thema sie haben.

**Comment by JJLo1** [comment]
Eventuell noch ein Fragment hinzfügen das dem Plant Fragment ähnelt, aber eben infos über einen bereich anzeigt
